### ISSUE TITLE
Feature Request: Smart case pattern search

### ISSUE THREAD

**Issue by ziontee113** [woosaaahh/sj.nvim#23] opened 2022-11-12 10:31 UTC
Hi @woosaaahh , I tried using `pattern_type = "vim_very_magic"` and still I can't get smart case to work. The current matching behavior seems to "lowercase everything". Does this setting already exists for sj? Thank you very much!

**Comment by woosaaahh** [comment] 2022-11-12 20:49
This should be fixed with 973b4b0 in `0.6`. 
By the way, `feat-no_separator` branch has been merged in `0.6`.

The problem is that most of the vim/neovim functions do not handle `smartcase`.
So now, if `smartcase` is used and the pattern has at least one uppercase, the case sensitivity is force by prefixing the pattern with "\C".

**Comment by woosaaahh** [comment] 2022-11-12 20:54
Could I close the issue ?

**Comment by woosaaahh** [comment] 2022-11-12 21:08
I take the :+1: for a yes. I'll re-open if needed !

**Closed by woosaaahh** 2022-11-12 21:08 UTC

**Comment by ziontee113** [comment] 2022-11-12 21:49
Thank you. Smart case works perfectly with 0.6 branch.
